---

- name: update apt cache
  apt:
    update_cache: yes
  changed_when: False
  when: ansible_os_family == 'Debian'

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  when: ansible_os_family == 'Debian'

- name: install pkg_mirror packages
  package:
    name: '{{ pkg_mirror_packages }}'
    state: present
