---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: Install pkg_mirror packages
  ansible.builtin.package:
    name: "{{ pkg_mirror_packages }}"
    state: present
