---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - role::pkg_mirror
    - role::pkg_mirror:install
    - role::pkg_mirror:config

- name: Set package url list debian
  ansible.builtin.set_fact:
    pkg_mirror_url_list: "{{ pkg_mirror_url_list_debian }}"
  when:
    - pkg_mirror_url_list_debian | length > 0
    - ansible_os_family == 'Debian'
  tags:
    - role::pkg_mirror
    - role::pkg_mirror:install

- name: Set package url list redhat
  ansible.builtin.set_fact:
    pkg_mirror_url_list: "{{ pkg_mirror_url_list_redhat }}"
  when:
    - pkg_mirror_url_list_redhat | length > 0
    - ansible_os_family == 'RedHat'
  tags:
    - role::pkg_mirror
    - role::pkg_mirror:install

- name: Import installation tasks
  ansible.builtin.import_tasks: installation.yml
  tags:
    - role::pkg_mirror
    - role::pkg_mirror:install

- name: Import configuration tasks
  ansible.builtin.import_tasks: configuration.yml
  tags:
    - role::pkg_mirror
    - role::pkg_mirror:config
